export const defaultTheme = {    
    colorTextLight: "#ffffff",
    colorTextDark: "#333333",
    colorDecor: "#fea18d",
    colorDecorSecond: "#f6ccc3",
    colorBackgroundDefault: "#000000",
    colorBackground: "#712073",
    fontFamily: '"RobotoCondensed","Arial",sans-serif',
    fontSizeDefault: "16px",
    lineHeight: "150%",
    fontWeight: "600",
    indent: "25px",
    pagePadding: "100px",
    pageWidth: "1480px",
}